[theme.templates.user.discord-translucence]
input_path  = "./templates/Translucence.theme.css"
output_path = "/home/maxfh/.config/BetterDiscord/themes/Translucence.theme.css"

[theme.templates.user.spotatui]
input_path  = "./templates/spotatui.yml"
output_path = "/home/maxfh/.config/spotatui/config.yml"
